# Module 6. Descriptive and Predictive Machine Learning

### Work performed by:
#### Rafael Haba Díaz 79030459K
#### Hugo Puerto Rosello 76884689J


## Task 5. Neuronal Network Notebook

# Lab assignment: perceptron training

In this assignment we will learn how perceptrons work and are trained.

## Guidelines

Throughout this notebook you will find empty cells that you will need to fill with your own code. Follow the instructions in the notebook and pay special attention to the following symbols.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>You will need to solve a question by writing your own code or answer in the cell immediately below or in a different file, as instructed.</td></tr>
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>This is a hint or useful observation that can help you solve this assignment. You should pay attention to these hints to better understand the assignment.</td></tr>
 <tr><td width="80"><img src="img/pro.png" style="width:auto;height:auto"></td><td>This is an advanced and voluntary exercise that can help you gain a deeper knowledge into the topic. Good luck!</td></tr>
</table>


During the assignment you will make use of several Python packages that might not be installed in your machine. If that is the case, you can install new Python packages with

    conda install PACKAGENAME
    
if you are using Python Anaconda. Else you should use

    pip install PACKAGENAME

You will need the following packages for this particular assignment. Make sure they are available before proceeding:

* **numpy**
* **scikit-learn**

Lastly, if you need any help on the usage of a Python function you can place the writing cursor over its name and press Caps+Shift to produce a pop-out with related documentation. This will only work inside code cells.

Let's go!

## The AND and OR problems

Let us define the AND and OR problems in the **dataset** form we will be using throughout this assignment. A dataset is composed of two matrices X and Y, storing respectively the **inputs** fed to the networks and the desired **outputs** or **targets** for such inputs. We will use numpy's arrays for this purpose:

In [7]:
import numpy as np
X_and = np.array([[1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
Y_and = np.array([[0], [0], [0], [1]])
X_or = X_and.copy()    # same inputs as for AND
Y_or = np.array([[0], [1], [1], [1]])
print(X_and)
print(Y_and)
print(X_or)
print(Y_or)

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0]
 [0]
 [0]
 [1]]
[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0]
 [1]
 [1]
 [1]]


Note that in the patterns above we have prepended a 1, so that the **weights** **w** also include the **bias** term b and a dot product of the form **w**·**x** actually computes **w**·**x** + b. Hence, in this particular case **w** = (b, w1, w2).

## Perceptrons

As you have seen in the theory, **perceptrons** are based on the **McCulloch-Pitts neuron**, which is a simplified version of a neuron in the human brain. The **activation function** of this neuron is 1 when its inputs are greater than or equal to 0, and 0 otherwise:

In [8]:
def step_activation(x):
    return 1*(x >= 0)   # multiply by 1 to change from boolean to int

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Figure out by yourself some values for <b>w</b> which solve the AND and OR problems. Store them in 2 variables called <b>w_and</b> and <b>w_or</b>.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
It may help if you print the points in (x1, x2) axes and interpret <b>w</b> and b as a hyperplane.
 </td></tr>
</table>

In [9]:

w_or=np.array([[-0.1,0,0,0],[-0.1,0,0,0],[-0.1,0,0,0]])
w_and=np.array([[-0.1,-0.1,-0.1,0],[-0.1,-0.1,-0.1,0],[-0.1,-0.1,-0.1,0]])


If your weights are correct, the following should output true:

In [10]:
print(np.all(step_activation(X_and.dot(w_and)) == Y_and.ravel()))
print(np.all(step_activation(X_or.dot(w_or)) == Y_or.ravel()))

True
True


Observe that we are already taking advantage of **matrix calculus**: by multiplying above the input matrix with the weight vector we can simultaneously obtain the perceptron's outputs for all patterns. Then we just need to compare whether those outputs are actually the desired ones.

Let us code now **Rosenblatt's perceptron**, so that it learns automatically **w_and** and **w_or** for us, as they are both **linearly separable** problems.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Implement Rosenblatt's perceptron in a function called **perceptron_learn**. The inputs should be the X and Y matrices for the problem to be solved, and the output should be the **w** vector comprising both the bias and the actual weights.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Rosenblatt's algorithm operates in an **online** way, so you cannot take advantage of matrix calculus, as the weight vector **w** may change with every single pattern.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
For comparison purposes, initialize **w = 0**. The function **zeros** in numpy does exactly this.
 </td></tr>
</table>

In [11]:
def perceptron_train(X,Y):
    w=np.zeros(len(X[0]))
    error=True
    n=len(X)
    epochs=0
    while(error):
        er=[]
        for i in range(n):
            o=step_activation(w.dot(X[i]))
            if (o!=Y[i][0]):
                w+=(Y[i]-o)*(X[i])
                er.append(True)
            else:
                er.append(False)
        epochs+=1
        error=np.any(er) # Any check if there are some True values
    print('Epochs: '+str(epochs))
    return w

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Test your implementation with the AND and OR problems. How many **epochs** are needed for convergence? What values do you get for **w_and** and **w_or**?
 </td></tr>
</table>

In [12]:
sol_and=perceptron_train(X_and,Y_and)
print(sol_and)

sol_or=perceptron_train(X_or,Y_or)
print(sol_or)

Epochs: 6
[-3.  2.  1.]
Epochs: 4
[-1.  1.  1.]


<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Verify that these new values for **w_and** and **w_or** do solve the respective problems. What happens if you initialize weights differently in **perceptron_learn**?
 </td></tr>
</table>

In [13]:
# VERIFICATION
print('Y_and obtained:',step_activation(X_and.dot(sol_and)),',','Real Y_and',Y_and.reshape(1,4))

print('Y_or obtained:',step_activation(X_or.dot(sol_or)),',','Real Y_or:',Y_or.reshape(1,4))

Y_and obtained: [0 0 0 1] , Real Y_and [[0 0 0 1]]
Y_or obtained: [0 1 1 1] , Real Y_or: [[0 1 1 1]]


In [14]:
## We check that w_and and w_or are solutions to our problem and calculate the number of epochs 6 and 4.

In [15]:
def perceptron_train2(X,Y):
    w=np.array([1,2,3])
    error=True
    n=len(X)
    epochs=0
    while(error):
        er=[]
        for i in range(n):
            o=step_activation(w.dot(X[i]))
            if (o!=Y[i][0]):
                w+=(Y[i]-o)*(X[i])
                er.append(True)
            else:
                er.append(False)
        epochs+=1
        error=np.any(er)
    print('Epochs: '+str(epochs))
    return w

In [16]:
print('AND Problem')
sol_and=perceptron_train2(X_and,Y_and)
print(sol_and)

print('OR Problem')
sol_or=perceptron_train2(X_or,Y_or)
print(sol_or)

AND Problem
Epochs: 4
[-3  2  1]
OR Problem
Epochs: 3
[-1  2  3]


#### If we change the initiation of the weights, mostly the solution of perceptron_learn will change. Though, in this case the AND Problem with the weight vector [1,2,3] has the same solution.
#### In the next cell, where we initialize the weights randomly, we can verify that the solution of perceptron_learn will be differents each time.

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Although Rosenblatt's algorithm states that all weights should be initialized to 0, you can initialize them randomly and convergence is still guaranteed.
 </td></tr>
</table>

In [17]:
import random

def perceptron_train_random(X,Y):
    long=len(X[0])
    w=np.zeros(long)
    for i in range(long):
        w[i]=random.random()
    error=True
    n=len(X)
    epochs=0
    while(error):
        er=[]
        for i in range(n):
            o=step_activation(w.dot(X[i]))
            if (o!=Y[i][0]):
                w+=(Y[i]-o)*(X[i])
                er.append(True)
            else:
                er.append(False)
        epochs+=1
        error=np.any(er)
    print('Epochs: '+str(epochs))
    return w

In [18]:
sol_and=perceptron_train_random(X_and,Y_and)
print(sol_and)

sol_or=perceptron_train_random(X_or,Y_or)
print(sol_or)

Epochs: 8
[-3.14487935  2.30412793  1.78149382]
Epochs: 2
[-0.1658249   0.17330735  0.9643701 ]


Let us compare our implementation with that of *scikit-learn*. The class which implements a perceptron is **Perceptron**:

In [19]:
from sklearn.linear_model import Perceptron
Perceptron()

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In order to make things comparable, we need no regularization and not shuffling the patterns in each epoch:

In [20]:
Perceptron(alpha = 0.0, shuffle=False)

Perceptron(alpha=0.0, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=False, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Train the scikit-learn perceptron for the AND and OR problems. Do you obtain the same values for **w_and** and **w_or**? Why/why not?
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Make sure that the parameter **n_iter** is at least as large as the number of epochs you obtained before.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Since *scikit-learn* splits weights (**coef_**) from biases (**intercept_**), we do not need to prepend anymore a 1 to the patterns. Be careful when feeding them to the **fit** method. Also, take this into account when checking the perceptron's output and comparing it to the one obtained with your method **perceptron_learn**.
 </td></tr>
</table>

### AND Problem

In [21]:
X=np.array([[0,0],[1,0],[0,1],[1,1]])
Y_and=Y_and.ravel()
                     
clf_and=Perceptron(alpha = 0.0, shuffle=False, random_state=0,max_iter=15)
clf_and.fit(X,Y_and)

clf_and.score(X,Y_and)

1.0

In [22]:
X_predict_and=np.array([[0,0],[0,1],[1,0],[1,1]])

clf_and.predict(X_predict_and)

array([0, 0, 0, 1])

In [23]:
# Calculate WEIGHTS
clf_and.coef_

array([[2., 3.]])

In [24]:
# Calculate BIASES
clf_and.intercept_

array([-4.])

### OR Problem

In [25]:
Y_or=Y_or.ravel()

clf_or=Perceptron(alpha = 0.0, shuffle=False, random_state=0,max_iter=10)
clf_or.fit(X,Y_or)

clf_or.score(X,Y_or)

1.0

In [26]:
X_predict_or=np.array([[0,0],[0,1],[1,0],[1,1]])

clf_or.predict(X_predict_or)

array([0, 1, 1, 1])

In [27]:
# WEIGHTS
clf_or.coef_

array([[2., 2.]])

In [28]:
# BIASES
clf_or.intercept_

array([-1.])

#### In both problems,we have obtained differents solutions. That is, because Sklearn's Perceptron algorithm returns a solution with the best possible fit or until it reaches the maximum number of iterations (epochs). Whereas, the Perceptron_learn algorithm returns the first solution it finds regardless of the fit.

## The XOR problem

As you know from the theory, Rosenblatt's perceptrons can only solve **linearly separable** problems. The AND and OR problems fall into this category, but the XOR problem does not.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Define the XOR problem in two matrices **X_xor**, **Y_xor** as we did above for the AND and OR problems.
 </td></tr>
</table>

In [29]:
X_xor = np.array([[1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
Y_xor = np.array([[0], [1], [1], [0]])

print(X_xor)
print(Y_xor)

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Verify that **perceptron_learn** does not converge when given the XOR problem.
 </td></tr>
</table>

#### If we run the next cell, we can check that the xor problem does not converge because we will have to stop it.

In [30]:
# perceptron_train(X_xor,Y_xor)

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Introduce some control to exit the function after a maximum number of epochs has been reached. Otherwise, execution will go on forever and can stall your PC.
 </td></tr>
</table>

In [31]:
n_max=100
def perceptron_train(X,Y):
    w=np.zeros(len(X[0]))
    error=True
    n=len(X)
    epochs=0
    while(error and epochs<n_max):
        er=[]
        for i in range(n):
            o=step_activation(w.dot(X[i]))
            if (o!=Y[i][0]):
                w+=(Y[i]-o)*(X[i])
                er.append(True)
            else:
                er.append(False)
        epochs+=1
        error=np.any(er) # Any check if there are some True values
    print('Epochs: '+str(epochs))
    if (epochs==n_max):
        print('The maximum number of iterations has been reached.')
    return w

In [32]:
perceptron_train(X_xor,Y_xor)

Epochs: 100
The maximum number of iterations has been reached.


array([ 0., -1.,  0.])

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Verify that scikit-learn's **Perceptron** does not converge either for the XOR problem.
 </td></tr>
</table>

In [33]:
####### INSERT YOUR CODE HERE
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y_xor = np.array([[0], [1], [1], [0]])

clf_xor=Perceptron(alpha = 0.0, shuffle=False, random_state=0,max_iter=50)
clf_xor.fit(X_xor,Y_xor.ravel())

clf_and.score(X_xor,Y_xor)

0.25

#### As the score of Perceptron it is very low, 0.25, we can conclude that it does not converge.

## Multilayer perceptrons

Because of the limitations perceptrons have, **multilayer perceptrons (MLPs)** are usually the choice when dealing with general problems. Let us use for now the following class for an MLP:

In [34]:
class MLP(object):

    def __init__(self, sizes):
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes[1:]]
        self.weights = [np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]

So that an MLP is initialized with a list specifying the sizes of the different layers. For instance:

In [35]:
sizes = [2, 3, 1]
net = MLP(sizes)

Creates an MLP with 2 input neurons, 3 hidden neurons and 1 output neuron. <u>Note also the convention of the weights: they are created in such a way that *weights[i][j][k]* denotes the weight connecting neuron k of the i-th layer to neuron j of the (i+1)-th layer</u> (assuming that input layer is layer 0, first hidden layer is layer 1, and so on). <u>The same logic applies for biases, so that *biases[i][j]* is the bias of neuron j of the (i+1)-th layer</u>.

In [36]:
print("Number of layers: " + str(net.num_layers))
print("Sizes of layers: " + str(net.sizes))
print("Biases of hidden layer: " + str(net.biases[0]))
print("Biases of output layer: " + str(net.biases[1]))
print("Weights between input and hidden layer: " + str(net.weights[0]))
print("Weights between hidden and output layer: " + str(net.weights[1]))

Number of layers: 3
Sizes of layers: [2, 3, 1]
Biases of hidden layer: [[-0.52252839]
 [-0.90327775]
 [ 0.74770374]]
Biases of output layer: [[0.54983734]]
Weights between input and hidden layer: [[ 1.68332299  0.78933507]
 [ 1.08478988 -0.14945763]
 [-0.37233909  1.3009939 ]]
Weights between hidden and output layer: [[ 0.45903975  0.49587337 -0.43259476]]


Let us assume for simplicity that all **activation functions** in our MLPs are going to be the *step_activation* defined above. Note that its implementation is vectorized, so that it works both for scalars and numpy arrays.

We can now easily program the **forward phase** of the **back-propagation** algorithm, that is, to input a pattern to the network and compute the network's outputs.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Implement the function **forward_phase(mlp, x)** that, given an MLP and an input vector **x**, computes the MLP's outputs when **x** is fed.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Take advantage of matrix calculus. Make sure to reshape the input vector to column form, so that the matrix-vector products do not raise errors.
 </td></tr>
</table>

In [37]:
####### INSERT YOUR CODE HERE
def forward_phase(mlp,x):
    aOld=x.copy()
    aNew=[]
    for i in range(net.num_layers-1):
        w=mlp.weights[i]
        b=mlp.biases[i]

        aNew=step_activation(w.dot(aOld)+b)

        aOld=aNew.copy()

    return aNew

Since weights in the MLP class are initialized randomly, it is very unlikely that these initial weights actually solve the XOR problem.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Check whether the MLP created above does solve XOR or not.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Again, the MLP class splits weights from biases, so you should not feed to the networks the ones prepended to the patterns.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Because of matrix calculus, the return of **forward_phase** will be in matrix form, when it is actually a scalar since there is only a single output neuron. You may need to flatten return values to compare them to the actual outputs.
 </td></tr>
</table>

In [38]:
####### INSERT YOUR CODE HERE
x=np.array([[0,1,0,1],[0,0,1,1]])
forward_phase(net,x)

array([[1, 1, 1, 1]])

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Build an MLP that actually solves XOR.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
You know from the theory that it suffices with a hidden layer of just 2 neurons. Because we have not coded any learning algorithm (we would need to program the whole back-propagation algorithm for that), you will have to set directly its weights and biases so that it does the job.
 </td></tr>
</table>

In [39]:
####### INSERT YOUR CODE HERE
class MLP_XOR(object):

    def __init__(self, sizes):
        self.num_layers = 3
        self.sizes = [2,2,1]
        self.biases = [np.array([[-2],[-3]]),np.array([[-2]])]
        self.weights = [np.array([[-4,5],[4,-6]]),np.array([[4,4]])]

In [40]:
net_XOR = MLP_XOR(sizes)

In [41]:
forward_phase(net_XOR,x)

array([[0, 1, 1, 0]])

Coding oneself the back-propagation algorithm is tedious and prone to errors (especially the **backward phase**), so it is only useful as an academic programming exercise. In practice, one resorts to implementations already available. *Scikit-learn* has two classes for MLPs, the **MLPClassifier** and the **MLPRegressor**:

In [42]:
from sklearn.neural_network import MLPClassifier, MLPRegressor
print(MLPClassifier())
print(MLPRegressor())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)
MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(100,), learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=200,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=None, shuffle=True, solver='adam',
             tol=0.0001, validation_fraction=0.1, ve

The only differences between the two are the **loss function** (**cross-entropy** for classification, **MSE** for regression) and the activation function of the output layer (**sigmoid** for classification, **identity** for regression). As you can see, the parameters used in construction are exactly the same ones, as well as the default values.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Discuss which of the above parameters you can identify with those seen in the theory slides and which you cannot.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/pro.png" style="width:auto;height:auto"></td><td>
Take some classification dataset used in the SVM assignments and fit an *MLPClassifier* by modifying the parameters you deem appropriate. Report the best network configuration you can find. Can you beat the best SVM you obtained for that problem?
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/pro.png" style="width:auto;height:auto"></td><td>
Repeat with some regression dataset and an *MLPRegressor*. Are you able to beat the SVR?
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Beware of normalizing your data before feeding them to an MLP. It is advised to use a pipeline with a *StandardScaler*.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Once in a pipeline, you can use grid search to try different choices for the MLP parameters.
 </td></tr>
</table>

<center>
~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.<br>
                          THIS IS THE END OF THE ASSIGNMENT<br>
~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.<br>
</center>